// src/routes/(app)/index.tsx
import { ListCard } from "@/components/lists/list-card";
import { ListSkeleton } from "@/components/skeletons/list-skeleton";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useListsWithLoading } from "@/queries/use-list";
import { Link, createFileRoute } from "@tanstack/react-router";
import { FileText, Heart, Upload } from "lucide-react";

export const Route = createFileRoute("/(app)/")({
	head: () => ({
		meta: [{ title: "Home - Load Order Library" }],
	}),
	component: HomePage,
});

const pageSize = 6;

function HomePage() {
	const { data: listsData, isLoading } = useListsWithLoading({ pageSize });

	return (
		<div className="space-y-6 container mx-auto">
			{/* Hero Section */}
			<div className="text-center space-y-6 py-12">
				<div className="space-y-4">
					<h1 className="text-4xl md:text-5xl font-bold text-primary">
						Load Order Library
					</h1>
					<p className="text-xl md:text-2xl text-muted-foreground max-w-3xl mx-auto">
						Share mod lists of - primarily Bethesda - games with
						other players
					</p>
				</div>

				<div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
					<Button asChild size="lg" className="gap-2">
						<Link to="/upload">
							<Upload className="h-5 w-5" />
							Upload Your List
						</Link>
					</Button>
					<Button
						asChild
						variant="outline"
						size="lg"
						className="gap-2"
					>
						<Link to="/lists">
							<FileText className="h-5 w-5" />
							Browse Lists
						</Link>
					</Button>

					<Button
						asChild
						variant="outline"
						size="lg"
						className="gap-2"
					>
						<Link to="/support">
							<Heart className="h-5 w-5" />
							Support the Site
						</Link>
					</Button>
				</div>
			</div>

			{/* Description Section */}
			<Card>
				<CardHeader>
					<CardTitle className="text-2xl">
						What is Load Order Library?
					</CardTitle>
				</CardHeader>
				<CardContent className="prose prose-lg max-w-none">
					<p className="text-muted-foreground leading-relaxed">
						Load Order Library is a website/tool to share mod lists
						of - primarily Bethesda - games with other players.
						Intended mostly for troubleshooting purposes, the site
						can be quite useful for YouTubers to have mod lists for
						each of their let's play characters, modlist authors to
						share the list of mods with others, and many other uses.
					</p>
				</CardContent>
			</Card>

			{/* Recent Lists Section */}
			<>
				<h2 className="text-3xl font-bold">Recent Lists</h2>
				{isLoading ? (
					<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
						{Array.from({ length: pageSize }).map((_, index) => (
							// biome-ignore lint/suspicious/noArrayIndexKey: skeleton items don't need stable keys
							<ListSkeleton key={index} />
						))}
					</div>
				) : listsData && listsData.data.length > 0 ? (
					<>
						<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
							{listsData.data.map((list) => (
								<ListCard key={list.slug} list={list} />
							))}
						</div>
						<div className="mt-6 text-center">
							<Button asChild variant="outline">
								<Link to="/lists">View All Lists</Link>
							</Button>
						</div>
					</>
				) : (
					<div className="text-center py-8 text-muted-foreground">
						No lists available yet. Why not{" "}
						<Link
							to="/upload"
							className="hover:underline text-primary font-bold"
						>
							create one
						</Link>
						?
					</div>
				)}
			</>
		</div>
	);
}

// src/routes/(app)/+page.svelte
<script lang="ts">
	import BrowseList from '$lib/components/lists/BrowseList.svelte';

	export let data;

	const { lists } = data;
</script>

<svelte:head>
	<title>Home - Load Order Library</title>
</svelte:head>

<div class="grid grid-cols-1 gap-10 md:grid-cols-2 md:gap-8">
	<article class="space-y-4">
		<header class="mb-4">
			<h1 class=" text-3xl font-bold text-green-500">Load Order Library</h1>
		</header>
		<section class="flex flex-col space-y-4 md:text-xl">
			<p class="leading-8 md:leading-8">
				Load Order Library is a website/tool to share mod lists of - primarily Bethesda - games with other
				players. Intended mostly for troubleshooting purposes, the site can be quite useful for YouTubers to
				have mod lists for each of their let's play characters, modlist authors to share the list of mods with
				others, and many other uses.
			</p>
			<p class="flex justify-center space-x-4 text-center font-bold">
				<a
					href="/upload"
					class="text-blue-600 hover:text-blue-400 active:text-blue-400 dark:text-blue-400 dark:hover:text-blue-600 dark:active:text-blue-600"
					>Create a List</a
				>

				<a
					href="/lists"
					class="text-blue-600 hover:text-blue-400 active:text-blue-400 dark:text-blue-400 dark:hover:text-blue-600 dark:active:text-blue-600"
					>Browse Lists</a
				>

				<a
					href="/compare"
					class="text-blue-600 hover:text-blue-400 active:text-blue-400 dark:text-blue-400 dark:hover:text-blue-600 dark:active:text-blue-600"
					>Compare Lists</a
				>
			</p>
		</section>
		<footer>
			<p>
				Find a bug? Please report it on <a
					href="https://github.com/phinocio/loadorderlibrary/issues"
					class="text-blue-600 hover:text-blue-400 active:text-blue-400 dark:text-blue-400 dark:hover:text-blue-600 dark:active:text-blue-600"
					>GitHub</a
				>
			</p>
			<p>
				Enjoy the site? Please consider supporting on
				<a
					href="https://patreon.com/phinocio"
					class="text-blue-600 hover:text-blue-400 active:text-blue-400 dark:text-blue-400 dark:hover:text-blue-600 dark:active:text-blue-600"
					>Patreon</a
				>
				or
				<a
					href="https://ko-fi.com/phinocio"
					class="text-blue-600 hover:text-blue-400 active:text-blue-400 dark:text-blue-400 dark:hover:text-blue-600 dark:active:text-blue-600"
					>Ko-fi</a
				>
			</p>
		</footer>
	</article>
	<article class="space-y-4">
		<header class="mb-4">
			<h1 class="text-3xl font-bold">Recent Lists</h1>
		</header>
		<section class="space-y-4">
			{#if lists.data.length > 0}
				{#each lists.data as list}
					<BrowseList {list} />
				{/each}
			{:else}
				<p>
					No lists available to show, why not <a
						href="/upload"
						class="text-blue-600 hover:text-blue-400 active:text-blue-400 dark:text-blue-400 dark:hover:text-blue-600 dark:active:text-blue-600"
					>
						create one?
					</a>
				</p>
			{/if}
		</section>
	</article>

	<!-- {#if user}
		{#if lists.data.length > 0}
			{#each lists.data as list}
				<ListSimple {list} />
			{/each}
		{:else}
			<p>
				You have no lists, why not <a
					href="/upload"
					class="font-bold text-green-600 hover:text-green-500 active:text-green-500 dark:text-green-500 dark:hover:text-green-600 dark:active:text-green-600"
					>create one.</a
				>
			</p>
		{/if}
	{:else}
		<p>You are not logged in.</p>
	{/if} -->
</div>

<style lang="postcss">
	:global(html) {
		background-color: theme(colors.gray.100);
	}
</style>
